#:import utils kivy.utils

<DashboardScreen>:
    BoxLayout:
        orientation: "vertical"
        canvas:
            Color:
                rgba: utils.get_color_from_hex("#0d1727")
            Rectangle:
                size: self.size
                pos: self.pos
        #--- start of top bar ---#
        BoxLayout:
            orientation: "horizontal"
            size_hint: (1, 0.03)
            spacing: '10'

            canvas:
                Color:
                    rgba: utils.get_color_from_hex("#121c2e")
                Rectangle:
                    size: self.size
                    pos: self.pos

            Spacer:
                size_hint: (0.75, 1)

            ImageButton:
                id: minimize_btn_id
                source: 'icons/arrow-up-circle.png'
                size_hint: (None, None)
                height: "25dp"
                width: "25dp"
                pos_hint: {"center_y": 0.48}
                on_release: app.minimize()

            ImageButton:
                id: close_btn_id
                source: 'icons/arrow-down-circle.png'
                size_hint: (None, None)
                height: "25dp"
                width: "25dp"
                pos_hint: {"center_y": 0.45}
                on_release: app.close()
            
            Spacer:
                size_hint: (0.01, 1)
        #--- end of top bar ---#
        Spacer:
            size_hint: (1, 0.04)

        

        
        BoxLayout:
            orientation: "vertical"
            size_hint: (0.96, 0.93)
            pos_hint: {"right": 0.98}

            #--- start of contry search and date bar ---#

            BoxLayout:
                orientation: "horizontal"
                size_hint: (1,0.1)

                Label:
                    text: "Enter country: "
                    size_hint: (0.15, 0.4)
                    color: utils.get_color_from_hex("#2b2f43")
                BoxLayout:
                    orientation: "vertical"
                    size_hint: (0.25, 0.4)

                    TextInput:
                        hint_text: ""
                        font_size: "13sp"
                        font_name: "barlow_medium"
                        size_hint: (1, 0.87)
                        background_color: 0, 0, 0, 0
                        foreground_color: 0.8, 0.8, 0.8, 1
                    BoxLayout:
                        size_hint: (1, 0.03)
                        canvas:
                            Color:
                                rgba: utils.get_color_from_hex("#2a2f44")
                            Rectangle:
                                size: self.size
                                pos: self.pos
                    Spacer:
                        size_hint: (1, 0.1)
                ImageButton:
                    source: 'icons/go.png'
                    size_hint: (0.1, 0.4)
                    allow_stretch: True
                    keep_aspect: False
                Spacer:
                    size: (0.55,1)
                Label:
                    id: date_id
                    text: "Auguest 25, 2020"
                    size_hint: (0.1, 0.5)
                    font_size: "15sp"
                    font_name: "barlow_medium"
                    color: utils.get_color_from_hex("#2b2f43")
                Spacer:
                    size_hint: (0.02, 1)
            #--- end  of contry search and date bar ---#
            Spacer:
                size_hint: (1, 0.05)

            #--- start  of comfirmed active and cases bar ---#

            BoxLayout:
                orientation: "horizontal"
                size_hint: (1,0.425)

                ## Start of confirmed cases widget
                BoxLayout:
                    orientation: "vertical"
                    size_hint: (0.74, 1)
                    sapcing: "10"

                    canvas:
                        Color:
                            rgba: utils.get_color_from_hex("#121c2e")
                        Rectangle:
                            size: self.size
                            pos: self.pos
  
                    BoxLayout:
                        orientation: "vertical"
                        size_hint: (1, 0.2)
                        Spacer:
                            size_hint: (1, 0.1)
                        Label:
                            text: "Confirmed Cases"
                            size_hint: (1, 0.9)
                            font_size: "15sp"
                            color: utils.get_color_from_hex("#47546e")
                    BoxLayout:
                        orientation: "vertical"
                        size_hint: (1, 0.6)
                        Label:
                            id: confirmed_cases_id
                            font_size: "200sp"
                            font_name: "roboto_medium"
                            text: "21,010"
                            color: utils.get_color_from_hex("#8695ad")
                    BoxLayout:
                        orientation: "horizontal"
                        size_hint: (1, 0.2)
                        Spacer:
                            size_hint: (0.45, 0.6)
                        Image:
                            source: 'icons/go.png'
                            size_hint: (0.05, 0.4)
                            pos_hint: {"center_y": 0.5}
                        Label:
                            text: "134"
                            font_size: "22sp"
                            font_name: "roboto_medium"
                            color: utils.get_color_from_hex("#500721")
                            size_hint: (0.05, 0.6)
                            pos_hint: {"center_y": 0.5}

                        Spacer:
                            size_hint: (0.45, 0.6)
                ## End of confirmed cases widget
                Spacer:
                    size_hint: (0.01, 1)
                BoxLayout:
                    orientation: "vertical"
                    size_hint: (0.25, 1)
                    sapcing: "10"

                    canvas:
                        Color:
                            rgba: utils.get_color_from_hex("#0d1727")
                        Rectangle:
                            size: self.size
                            pos: self.pos

                    BoxLayout:
                        orientation: "vertical"
                        size_hint: (1, 0.5)
                        spaceing: "1"
                        canvas:
                            Color:
                                rgba: utils.get_color_from_hex("#121c2e")
                            Rectangle:
                                size: self.size
                                pos: self.pos
                        Spacer:
                            size_hint:(1, 0.1)
                        Label:
                            text: "Confirmed Deaths"
                            font_size: "22sp"
                            font_name: "roboto_medium"
                            color: utils.get_color_from_hex("#47546e")
                            size_hint: (1, 0.1)
                        Label:
                            id: confirmed_deaths_id
                            font_size: "22sp"
                            font_name: "roboto_medium"
                            color: utils.get_color_from_hex("#47546e")
                            size_hint: (1, 0.5)
                        BoxLayout:
                            orientation: "horizontal"
                            size_hint: (1, 0.2)

                            Spacer:
                                size_hint: (0.4, 0.6)
                            Image:
                                source: 'icons/up.png'
                                size_hint: (0.05, 0.4)
                                pos_hint: {"conter_y": 0.5}

                            Label:
                                text: "212"
                                font_size: "22sp"
                                size_hint: (0.2, 0.6)
                                font_name: "roboto_medium"
                                color: utils.get_color_from_hex("#500721")
                                pos_hint:{"center_y": 0.5}
                            Spacer:
                                size_hint: (0.35, 0.6)
                    # end of middle right up section 
                    Spacer:
                        size_hint: (1, 0.01)
        
                    # start of middle right down section
                    BoxLayout:
                        orientation: "vertical"
                        size_hint: (1, 0.5)
                        spaceing: "1"
                        canvas:
                            Color:
                                rgba: utils.get_color_from_hex("#121c2e")
                            Rectangle:
                                size: self.size
                                pos: self.pos
                        Spacer:
                            size_hint:(1, 0.1)
                        Label:
                            text: "Confirmed Deaths"
                            font_size: "22sp"
                            font_name: "roboto_medium"
                            color: utils.get_color_from_hex("#47546e")
                            size_hint: (1, 0.1)
                        Label:
                            id: confirmed_deaths_id
                            font_size: "22sp"
                            font_name: "roboto_medium"
                            color: utils.get_color_from_hex("#47546e")
                            size_hint: (1, 0.5)
                        BoxLayout:
                            orientation: "horizontal"
                            size_hint: (1, 0.2)

                            Spacer:
                                size_hint: (0.4, 0.6)
                            Image:
                                source: 'icons/up.png'
                                size_hint: (0.05, 0.4)
                                pos_hint: {"conter_y": 0.5}

                            Label:
                                text: "212"
                                font_size: "22sp"
                                size_hint: (0.2, 0.6)
                                font_name: "roboto_medium"
                                color: utils.get_color_from_hex("#500721")
                                pos_hint:{"center_y": 0.5}
                            Spacer:
                                size_hint: (0.35, 0.6)
                    # end of middle right down section
                    
                    


                      

            #--- end  of comfirmed active and cases bar ---#
            
            BoxLayout:
                orientation: "horizontal"
                size_hint: (1,0.355)